export { default as Home } from "./Home"
export { default as About } from "./About"
export { default as Services }  from "./Services"
export { default as Contact } from "./Contact"
export { default as Advertising } from "./Advertising"
export { default as Marketing } from "./Marketing"
export { default as GoogleAds} from "./GoogleAds"
export { default as FacebookAds } from "./FacebookAds"